[target.aarch64-unknown-linux-ohos]
linker = "C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/llvm/bin/clang.exe"
ar = "C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/llvm/bin/llvm-ar.exe"
rustflags = [
    "-C", "link-arg=--target=aarch64-linux-ohos",
    "-C", "link-arg=--sysroot=C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/sysroot",
    "-C", "link-arg=-L",
    "-C", "link-arg=C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/llvm/lib/aarch64-linux-ohos",
    "-C", "link-arg=-lc++_static",
    "-C", "link-arg=-lc++abi",
]

[target.x86_64-unknown-linux-ohos]
linker = "C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/llvm/bin/clang.exe"
ar = "C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/llvm/bin/llvm-ar.exe"
rustflags = [
    "-C", "link-arg=--target=x86_64-linux-ohos",
    "-C", "link-arg=--sysroot=C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/sysroot",
    "-C", "link-arg=-L",
    "-C", "link-arg=C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/llvm/lib/x86_64-linux-ohos",
    "-C", "link-arg=-lc++_static",
    "-C", "link-arg=-lc++abi",
]

[env]
CC_aarch64-unknown-linux-ohos = "C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/llvm/bin/clang.exe"
AR_aarch64-unknown-linux-ohos = "C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/llvm/bin/llvm-ar.exe"
CFLAGS_aarch64-unknown-linux-ohos = "--sysroot=C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/sysroot --target=aarch64-linux-ohos"
CC_x86_64-unknown-linux-ohos = "C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/llvm/bin/clang.exe"
AR_x86_64-unknown-linux-ohos = "C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/llvm/bin/llvm-ar.exe"
CFLAGS_x86_64-unknown-linux-ohos = "--sysroot=C:/PROGRA~1/Huawei/DEVECO~1/sdk/default/openharmony/native/sysroot --target=x86_64-linux-ohos"
